### ISSUE TITLE
Missing Semicolon in package declarative parser creates funny error message

### ISSUE THREAD

**Issue by g0t00** [vhdl-linter/vhdl-linter#261] opened 2023-02-12 14:10 UTC
```vhdl
package test_pkg is
  constant TEST : integer := 5
end package;
 
```
![image](https://user-images.githubusercontent.com/38039/218316009-64e58f6e-743f-4412-b2fc-62181ae94688.png)

**Comment by Nik-Sch** [comment] 2023-02-13 16:36
I am pretty sure that this is a duplicate of #256

**Comment by g0t00** [comment] 2023-02-13 16:51
It is at least related.  But in this example the semicolon is missing. In the other on the declaration is starting wrong? But if we are lucky fix fixes both

**Closed** 2023-02-20 15:28 UTC
Labels: bug, duplicate
