### ISSUE TITLE
[Bug] Cannot detect `when x"XXX"` condition in `case` statement

### ISSUE THREAD

**Issue by pidgeon777** [vhdl-linter/vhdl-linter#289] opened 2023-02-23 11:13 UTC
Sample code:

```vhdl
case cnt_lval_fldgen is
	when x"0014" =>
		data_int <= "0000000" & FIRST_CODE_N2(3);
	when "0100000000000001" =>
		data_int <= FOURTH_CODE_EAV_VALID_N1(2 downto 0) & FOURTH_CODE_EAV_VALID_N0 & "0";
	-----------------------------
	when others =>
		-- data_int <= DATA_FLDGEN;
		data_int <= "01100110";
end case;
```

![image](https://user-images.githubusercontent.com/13739892/220890170-4d42daf6-2745-468e-b9d5-fe898154574b.png)

**Comment by g0t00** [comment] 2023-02-23 11:19
Thank you for reporting. I think this is duplicate of #226
@Nik-Sch Can you confirm?
On the other hand the binary bitstring is working.

**Comment by Nik-Sch** [comment] 2023-02-23 13:35
Eh, yeah this is a duplicate of #226.
The reason why the bit string without 'x' is shown correctly is because we currently treat stringLiterals (`".*"`) and bitstring literals (`x".*"`) differently... This should definitely be streamlined

**Closed** 2023-02-27 22:30 UTC
Labels: duplicate

**Comment by pidgeon777** [comment] 2023-02-28 08:45
Works good 👍.

**Comment by Nik-Sch** [comment] 2023-02-28 09:00
Nice to hear! Should also be released in 1.5.11 now.
